version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: ./conf/Dockerfile
    ports:
      - "8181:80"
    volumes:
      - ./conf/sri.asir4all.ss.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/claves.txt:/etc/apache2/claves.txt
      - ./web/servidor.php:/var/www/html/servidor.php
      - ./conf/clavesdigest.txt:/etc/apache2/clavesdigest.txt

